options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image using GitHub commit SHA
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - varun-docker
      - -t
      - us-central1-docker.pkg.dev/varun-484410/varun-webapp/varun-docker:$SHORT_SHA
      - .

  # Step 2: Push commit-tagged image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/varun-484410/varun-webapp/varun-docker:$SHORT_SHA

  # Step 3: Tag same image as prod
  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - us-central1-docker.pkg.dev/varun-484410/varun-webapp/varun-docker:$SHORT_SHA
      - us-central1-docker.pkg.dev/varun-484410/varun-webapp/varun-docker:prod

  # Step 4: Push prod tag
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/varun-484410/varun-webapp/varun-docker:prod

  # Step 5: Deploy to VM via SSH
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - ssh
      - varun-app
      - --zone=us-central1-c
      - --project=varun-484410
      - --command
      - |
        set -e
        docker pull us-central1-docker.pkg.dev/varun-484410/varun-webapp/varun-docker:prod
        docker stop varun-docker || true
        docker rm varun-docker || true
        docker run -d \
          --name varun-docker \
          -p 80:80 \
          us-central1-docker.pkg.dev/varun-484410/varun-webapp/varun-docker:prod
        sleep 3
        docker ps | grep varun-docker

images:
  - us-central1-docker.pkg.dev/varun-484410/varun-webapp/varun-docker:$SHORT_SHA
  - us-central1-docker.pkg.dev/varun-484410/varun-webapp/varun-docker:prod
